### ISSUE TITLE
(7) SpringBoot

### ISSUE THREAD

**Issue by Linho1150** [Linho1150/SpringBoot_Deploy1#6]
# SpringBoot & Github Actions
## Spring Boot로 HelloWorld 프로젝트를 생성 후 Root Path("/")요청시 HelloWorld가 출력되는 프로젝트 생성
```
@RestController
@RequestMapping("/")
public class HelloworldController {
    @RequestMapping()
    @GetMapping()
    public String main(){
        return "Hello World";
    }
}

```
## Ouput되는 Jar파일의 이름을 고정하기 위해 build.gradle파일 수정. 아래 코드 추가
``` 
bootJar{
    archivesBaseName = 'HelloWorld'
    archiveFileName = 'helloworld.jar'
    archiveVersion = "0.0.1"
}

jar {
    enabled = false
}
```
## 루트 경로에 appspec.yml 파일추가. CodeDeploy가 수행을 완료하면 AfterInstall과 AppllicationStart를 실행
```
version: 0.0
os: linux

files:
  - source:  /
    destination: /home/ubuntu/app
    overwrite: yes

permissions:
  - object: /
    pattern: "**"
    owner: ubuntu
    group: ubuntu

hooks:
  AfterInstall:
    - location: scripts/stop.sh
      timeout: 60
      runas: ubuntu
  ApplicationStart:
    - location: scripts/start.sh
      timeout: 60
      runas: ubuntu
```

### scripts/start.sh
```
#!/usr/bin/env bash

PROJECT_ROOT="/home/ubuntu/app" #코드가 주입되는 경로
JAR_FILE="$PROJECT_ROOT/helloworld.jar" #build.gradle에서 설정한 파일명으로 변경

APP_LOG="$PROJECT_ROOT/application.log"
ERROR_LOG="$PROJECT_ROOT/error.log"
DEPLOY_LOG="$PROJECT_ROOT/deploy.log"

TIME_NOW=$(date +%c)

echo "$TIME_NOW > $JAR_FILE 파일 복사" >> $DEPLOY_LOG
cp $PROJECT_ROOT/build/libs/*.jar $JAR_FILE

echo "$TIME_NOW > $JAR_FILE 파일 실행" >> $DEPLOY_LOG
nohup java -jar $JAR_FILE > $APP_LOG 2> $ERROR_LOG &

CURRENT_PID=$(pgrep -f $JAR_FILE)
echo "$TIME_NOW > 실행된 프로세스 아이디 $CURRENT_PID 입니다." >> $DEPLOY_LOG
```
### scripts/stop.sh
```
#!/usr/bin/env bash

PROJECT_ROOT="/home/ubuntu/app" #코드가 주입되는 경로
JAR_FILE="$PROJECT_ROOT/helloworld.jar" #build.gradle에서 설정한 파일명으로 변경

DEPLOY_LOG="$PROJECT_ROOT/deploy.log"

TIME_NOW=$(date +%c)

CURRENT_PID=$(pgrep -f $JAR_FILE)

if [ -z $CURRENT_PID ]; then
  echo "$TIME_NOW > 현재 실행중인 애플리케이션이 없습니다" >> $DEPLOY_LOG
else
  echo "$TIME_NOW > 실행중인 $CURRENT_PID 애플리케이션 종료 " >> $DEPLOY_LOG
  kill -15 $CURRENT_PID
fi
```
