### ISSUE TITLE
(8) Github Actions

### ISSUE THREAD

**Issue by Linho1150** [Linho1150/SpringBoot_Deploy1#7]
# Github Actions
## Github Actions의 WorkFlow(.github/workflows/CI.yml)추가. 수정해야할 부분 주석처리
```
name: Deploy to Amazon EC2

on:
  push:
    branches:
      - master
env:
  S3_BUCKET_NAME: backble //S3의 버킷명
  CODE_DEPLOY_APPLICATION_NAME: SpringCICD //CodeDeploy생성시 어플리케이션명
  CODE_DEPLOY_DEPLOYMENT_GROUP_NAME: SpringCICD //CodeDeploy를 생성후 어플리케이션 내부의 배포그룹명

permissions:
  contents: read

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    environment: production

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up JDK 17 //프로젝트 JDK에 맞는 버전 설정 (build.gradle 참고)
        uses: actions/setup-java@v1
        with:
          java-version: '17' //프로젝트 JDK에 맞는 버전 설정 (build.gradle 참고)

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Build with Gradle
        run: ./gradlew clean build

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }} //IAM의 ACCESS KEY ID를 GITHUB SECRET KEY로 설정
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }} //GITHUB SECRET KEY로 설정
          aws-region: ${{ secrets.AWS_REGION }} //GITHUB SECRET KEY중 AWS_REGION의 값을 ap-northeast-2로 설정

      - name: Upload to AWS S3
        run: |
          aws deploy push \
            --application-name ${{ env.CODE_DEPLOY_APPLICATION_NAME }} \
            --ignore-hidden-files \
            --s3-location s3://$S3_BUCKET_NAME/$GITHUB_SHA.zip \
            --source .

      - name: Deploy to AWS EC2 from S3
        run: |
          aws deploy create-deployment \
            --application-name ${{ env.CODE_DEPLOY_APPLICATION_NAME }} \
            --deployment-config-name CodeDeployDefault.AllAtOnce \
            --deployment-group-name ${{ env.CODE_DEPLOY_DEPLOYMENT_GROUP_NAME }} \
            --s3-location bucket=$S3_BUCKET_NAME,key=$GITHUB_SHA.zip,bundleType=zip
```
