### ISSUE TITLE
(8) appspec.yml 설정

### ISSUE THREAD

**Issue by Linho1150** [Linho1150/SpringBoot_Deploy1#8]
# CodeDeploy용 appspec.yml 파일
## 루트 경로에 appspec.yml 파일추가. CodeDeploy가 수행을 완료하면 AfterInstall과 AppllicationStart를 실행
```
version: 0.0
os: linux

files:
  - source:  /
    destination: /home/ubuntu/app
    overwrite: yes

permissions:
  - object: /
    pattern: "**"
    owner: ubuntu
    group: ubuntu

hooks:
  AfterInstall:
    - location: scripts/stop.sh
      timeout: 60
      runas: ubuntu
  ApplicationStart:
    - location: scripts/start.sh
      timeout: 60
      runas: ubuntu
```
